all: clear clean compile run 

compile: 
	@echo Compiling.......
	javac ./homework6/*.java
	@echo
	

run:
	@echo Running...... 
	java homework6.Main
	@echo

clean: 
	@echo Cleanning..... 
	rm -f ./homework6/*.class
	@echo

clear:
	clear


