all: clear clean compile run 

compile: 
	@echo Compiling.......
	javac ./homework5/*.java
	@echo
	

run:
	@echo Running...... 
	java homework5.Main
	@echo

clean: 
	@echo Cleanning..... 
	rm -f ./homework5/*.class
	@echo

clear:
	clear


