all: clear clean compile run 

compile: 
	@echo Compiling.......
	javac ./homework7/*.java
	@echo
	

run:
	@echo Running...... 
	java homework7.Main
	@echo

clean: 
	@echo Cleanning..... 
	rm -f ./homework7/*.class
	@echo

clear:
	clear

runtime:
	@echo Running Times...... 
	java homework7.runTimes
	@echo
	


