all: clear clean compile run 

compile: 
	@echo Compiling.......
	javac ./homework4/*.java
	@echo
	

run:
	@echo Running...... 
	java homework4.Main
	@echo

clean: 
	@echo Cleanning..... 
	rm -f ./homework4/*.class
	@echo

clear:
	clear


